[metadata]
org = "Uptime"
scope = "dev"
maintainer = "Andrelin"

[helmRepos]
stable = "https://charts.helm.sh/stable"
jenkins = "https://charts.jenkins.io"

[namespaces.core.labels]
env = "core"

[apps.jenkins]
name = "jenkins"
description = "Jenkins"
namespace = "core"
enabled = true
chart = "jenkins/jenkins"
version = "2.17.0"
valuesFiles = [ "values/jenkins.yaml",]
purge = true
test = false
