[metadata]
org = "Uptime"
scope = "dev"
maintainer = "Andrelin"

[helmRepos]
stable = "https://charts.helm.sh/stable"
jenkins = "https://charts.jenkins.io"
confluentinc = "https://confluentinc.github.io/cp-helm-charts/"

[namespaces.core.labels]
env = "core"

[apps.jenkins]
name = "jenkins"
description = "Jenkins"
namespace = "core"
enabled = false
chart = "jenkins/jenkins"
version = "2.17.0"
valuesFiles = [ "values/jenkins.yaml",]
purge = true
test = false

[apps.chartmuseum]
name = "chartmuseum"
description = "chartmuseum"
namespace = "core"
enabled = false
chart = "stable/chartmuseum"
version = "2.14.0"
valuesFiles = [ "values/chartmuseum.yaml",]
purge = true
test = false

[apps.confluent-platform]
name = "confluent-platform"
description = "confluent-platform"
namespace = "core"
enabled = false
chart = "confluentinc/cp-helm-charts"
version = "0.5.0"
valuesFiles = [ "values/confluent-platform.yaml",]
purge = true
test = false
